### ISSUE TITLE
?

### ISSUE THREAD

**Issue by anthonyzutter** [realstrings/Rust-recoil-compensation#1]
Was this supposed to be there?
https://github.com/realstrings/Rust-recoil-compensation/blob/d9e6e21b2328bcf5175aa9a657fc7bd680e14857/main.py#L85
Can you also please add me on discord: Anthonyy#4737

**Comment by realstrings** [comment]
Yea it was experiment with lost x,y points, Its declared outta function so i can change it in functions using global flag
